name: Node.js CI

on:
  push:
    branches: [ "hashir-104" ]
  pull_request:
    branches: [ "hashir-104" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: find the directories
      run : dir
    - name: directory change
      run: cd you-anime
    - run : dir
    - name: Install dependencies
      run: npm install
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
   
    - run: npm run build --if-present
