name: Node.js CI

on:
  push:
    branches: [ "hashir-104" ]
  pull_request:
    branches: [ "hashir-104" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
   
    - uses: actions/checkout@v3
    - name: find the directories
      run : dir
    
    - run : dir
    - name: Install dependencies
      working-directory: ./you-anime
      run: npm install
    - name: Build
      working-directory: ./you-anime
      run:
           npm run deploy 
